import "./inspinia/css/bootstrap.min.css";
import "./inspinia/font-awesome/css/font-awesome.css";
import "./inspinia/css/animate.css";
import "./inspinia/css/style.css";

export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home} from "./Home";
export { default as About} from "./About";
export { default as Contact} from "./Contact";
export { default as Blog} from "./blog/Blog";
export { default as Posts} from "./blog/Posts";
export { default as Post} from "./blog/Post";
export { default as Login} from "./Login";
export { default as Rejestruj} from "./Rejestruj";
export { default as Ekranglowny} from "./Ekranglowny";
export { default as Pusta_Strona} from "./Pusta_Strona";
export { default as RozpocznijSeriePomiarowa} from "./RozpocznijSeriePomiarowa";
export { default as OknoPomiaru} from "./OknoPomiaru";
export { default as OknoSeriiPomiarow} from "./OknoSeriiPomiarow";